name: pipeline

on: 
  push:
  deployment:
  release:
    types: [created]
  pull_request:
    types: [opened, reopened]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: 'dev'
        options:
        - dev
        - stg
        - prd
        - sbx
        - dry

jobs:

  SVC:
    uses:  andrebrito16/ab-actions-pipelines/.github/workflows/svc.yml@master
    with:
      mainBranch: master
      platforms: linux/amd64,linux/arm64
      staticAnalysis: false
      containerRegistry: registry.gitlab.com/andrebrito16/teste-container-registry
      nodeMatrix: '[14, 17]'
      environmentsAsNamespaces: true #