name: pipeline

on: 
  push:
  deployment:
  release:
    types: [created]
  pull_request:
    types: [opened, reopened]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: choice
        default: 'dev'
        options:
        - dev
        - stg
        - prd
        - sbx
        - dry

jobs:

  APP:
    uses: andrebrito16/ab-app-react/.github/workflows/svc.yml@main
    secrets: inherit
    with:
      mainBranch: main
      platforms: linux/amd64,linux/arm64
      containerRegistry: registry.gitlab.com/andrebrito16/teste-container-registry
      environmentsAsNamespaces: true